name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry and git-index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify formatting
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --all --locked

      - name: Build release
        run: cargo build --release --locked

      - name: Package crate
        run: cargo package --allow-dirty --no-verify

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload crate asset
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/package
          asset_name: genix-${{ github.ref_name }}.crate
          asset_content_type: application/gzip

      - name: Done
        run: echo "Release created for ${{ github.ref_name }}"
